### ISSUE TITLE
[BUG]: leave before complete

### ISSUE THREAD

**Issue by vijhay-kishar** [Lost-In-Dark/TG-MusicPlayer#7]
Hello, I'm facing a problem when playing music (use the !play command), why when I use the !play feature (music only) the song is not completed, I mean the userbot leaving Video Chat before the song is finished, but when I use the !vplay command is normal the video is stream until complete not like !play command, please fix 🥺 thank you.

**Comment by Lost-In-Dark** [comment]
> Hello, I'm facing a problem when playing music (use the !play command), why when I use the !play feature (music only) the song is not completed, I mean the userbot leaving Video Chat before the song is finished, but when I use the !vplay command is normal the video is stream until complete not like !play command, please fix 🥺 thank you.

It's a FFmpeg Library Side Issue. Can just wait for Updates from their side

**Comment by vijhay-kishar** [comment]
> > Hello, I'm facing a problem when playing music (use the !play command), why when I use the !play feature (music only) the song is not completed, I mean the userbot leaving Video Chat before the song is finished, but when I use the !vplay command is normal the video is stream until complete not like !play command, please fix pleading_face thank you.
> 
> It's a FFmpeg Library Side Issue. Can just wait for Updates from their side

Ahh okay I see, thanks for the response 🙏🏻

**Comment by saucedbeacon** [comment]
Hi, may you look up at this issue now? Other repositories providing this same service is completely fine.
